import type { BuilderContent, RegisteredComponent } from '../types.js';
type $$ComponentProps = {
    content?: BuilderContent | null;
    model?: string;
    data?: Record<string, unknown>;
    context?: Record<string, unknown>;
    apiKey?: string;
    apiHost?: string;
    apiVersion?: string;
    customComponents?: RegisteredComponent[];
    canTrack?: boolean;
    locale?: string;
    linkComponent?: unknown;
    blocksWrapper?: unknown;
    blocksWrapperProps?: Record<string, unknown>;
    contentWrapper?: string;
    contentWrapperProps?: Record<string, unknown>;
    nonce?: string;
    isNestedRender?: boolean;
    showContent?: boolean;
    isSsrAbTest?: boolean;
};
declare const ContentView: import("svelte").Component<$$ComponentProps, {}, "">;
type ContentView = ReturnType<typeof ContentView>;
export default ContentView;
