export type FormState = 'unsubmitted' | 'sending' | 'success' | 'error';
import type { Snippet } from 'svelte';
import { type Writable } from 'svelte/store';
import type { BuilderBlock, RegisteredComponents } from '../types.js';
type $$ComponentProps = {
    builderContext: Writable<Record<string, any>>;
    builderBlock?: BuilderBlock;
    builderComponents?: RegisteredComponents;
    builderLinkComponent?: unknown;
    previewState?: FormState;
    sendWithJs?: boolean;
    sendSubmissionsTo?: string;
    action?: string;
    customHeaders?: Record<string, string>;
    contentType?: string;
    sendSubmissionsToEmail?: string;
    name?: string;
    method?: string;
    errorMessagePath?: string;
    resetFormOnSubmit?: boolean;
    successUrl?: string;
    validate?: boolean;
    attributes?: Record<string, unknown>;
    errorMessage?: BuilderBlock[];
    sendingMessage?: BuilderBlock[];
    successMessage?: BuilderBlock[];
    children?: Snippet;
    [k: string]: unknown;
};
declare const Form: import("svelte").Component<$$ComponentProps, {}, "">;
type Form = ReturnType<typeof Form>;
export default Form;
