import type { Snippet } from 'svelte';
import type { BuilderBlock } from '../types.js';
type $$ComponentProps = {
    image?: string;
    src?: string;
    srcset?: string;
    noWebp?: boolean;
    aspectRatio?: number;
    highPriority?: boolean;
    altText?: string;
    title?: string;
    backgroundPosition?: string;
    backgroundSize?: string;
    className?: string;
    sizes?: string;
    builderBlock?: BuilderBlock;
    fitContent?: boolean;
    children?: Snippet;
    [k: string]: unknown;
};
declare const Image: import("svelte").Component<$$ComponentProps, {}, "">;
type Image = ReturnType<typeof Image>;
export default Image;
